# Autogenerated wrapper script for libmeddly_c_jll for aarch64-linux-gnu-cxx11
export libmeddly_c

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("libmeddly_c")
JLLWrappers.@declare_library_product(libmeddly_c, "libmeddly_c.so")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libmeddly_c,
        "lib/libmeddly_c.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
