# Autogenerated wrapper script for libmeddly_c_jll for aarch64-apple-darwin
export libmeddly_c

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("libmeddly_c")
JLLWrappers.@declare_library_product(libmeddly_c, "@rpath/libmeddly_c.dylib")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libmeddly_c,
        "lib/libmeddly_c.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
